#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VampGPTBack.AccesoDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="pruebaMobil")]
	public partial class vampLinQDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public vampLinQDataContext() : 
				base(global::VampGPTBack.Properties.Settings.Default.pruebaMobilConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public vampLinQDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public vampLinQDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public vampLinQDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public vampLinQDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CrearCuenta")]
		public int CrearCuenta([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string correoCuenta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string contrasenaCuenta)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), correoCuenta, contrasenaCuenta);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.VerificarCuenta")]
		public int VerificarCuenta([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string correoCuenta)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), correoCuenta);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ConsultarPrompt")]
		public ISingleResult<ConsultarPromptResult> ConsultarPrompt([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idPrompt)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idPrompt);
			return ((ISingleResult<ConsultarPromptResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CrearJugador")]
		public int CrearJugador([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idCuenta, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string numbreJugador)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCuenta, numbreJugador);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GuardarAccesorio")]
		public int GuardarAccesorio([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombAccesorio", DbType="VarChar(255)")] string nombAccesorio, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PrecioAccesorio", DbType="Int")] System.Nullable<int> precioAccesorio)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombAccesorio, precioAccesorio);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GuardarPrompt")]
		public int GuardarPrompt([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PromptText", DbType="VarChar(255)")] string promptText, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string tipoPrompt, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> promptNumero, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idJuego)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), promptText, tipoPrompt, promptNumero, idJuego);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GuardarSombrero")]
		public int GuardarSombrero([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombSombrero", DbType="VarChar(255)")] string nombSombrero, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PrecioSomb", DbType="Int")] System.Nullable<int> precioSomb)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombSombrero, precioSomb);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GuardarTraje")]
		public int GuardarTraje([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombTraje", DbType="VarChar(255)")] string nombTraje, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PrecioTraje", DbType="Int")] System.Nullable<int> precioTraje)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombTraje, precioTraje);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class ConsultarPromptResult
	{
		
		private string _PromptTexto;
		
		private string _tipo_Prompt;
		
		private int _prompt_Numero;
		
		private System.DateTime _fecha_Prompt;
		
		public ConsultarPromptResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PromptTexto", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string PromptTexto
		{
			get
			{
				return this._PromptTexto;
			}
			set
			{
				if ((this._PromptTexto != value))
				{
					this._PromptTexto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_Prompt", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string tipo_Prompt
		{
			get
			{
				return this._tipo_Prompt;
			}
			set
			{
				if ((this._tipo_Prompt != value))
				{
					this._tipo_Prompt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prompt_Numero", DbType="Int NOT NULL")]
		public int prompt_Numero
		{
			get
			{
				return this._prompt_Numero;
			}
			set
			{
				if ((this._prompt_Numero != value))
				{
					this._prompt_Numero = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_Prompt", DbType="DateTime NOT NULL")]
		public System.DateTime fecha_Prompt
		{
			get
			{
				return this._fecha_Prompt;
			}
			set
			{
				if ((this._fecha_Prompt != value))
				{
					this._fecha_Prompt = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
